import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <header className="fixed text-slate-200 bg-slate-700 top-0 left-0 w-screen h-16 px-24 flex items-center justify-between">
        <h1 className="text-2xl font-bold">LOGO</h1>
        <ul className="flex gap-5 font-semibold">
          <Link href="/">Home</Link>
          <Link href="/Posts">Get</Link>
        </ul>
      </header>
      <body className={inter.className}>
        {children}
  
      </body>
    </html>
  );
}
